### ISSUE TITLE
Centos repo is deprecated and GPG key does not work

### ISSUE THREAD

**Issue by v1peractual** [ncsa/puppet-profile_duo#5]
The centos repo is deprecated and the GPG key does not work. https://duo.com/docs/duounix

Please switch to RedHat.

**Comment by v1peractual** [comment]
profile_duo::yumrepo_baseurl: "https://pkg.duosecurity.com/CentOS/$releasever/$basearch"

should be profile_duo::yumrepo_baseurl: "https://pkg.duosecurity.com/RedHat/$releasever/$basearch"

**Comment by bsper2** [comment]
This is fixed in https://github.com/ncsa/puppet-profile_duo/pull/6
